!pip install imutils

In [46]:
!pwd

/c/Users/Admin


In [47]:
import cv2
import numpy as np
import imutils

In [83]:
# Load an image
img = cv2.imread('cap.jpg')
#img = cv2.imread('circles0.jpg')
assert img is not None, "file could not be read, check with os.path.exists()"
img

array([[[197, 191, 184],
        [197, 191, 184],
        [194, 191, 183],
        ...,
        [197, 195, 194],
        [195, 193, 192],
        [195, 193, 192]],

       [[196, 190, 183],
        [196, 190, 183],
        [193, 190, 182],
        ...,
        [197, 195, 194],
        [196, 194, 193],
        [196, 194, 193]],

       [[193, 190, 182],
        [193, 190, 182],
        [192, 189, 181],
        ...,
        [196, 194, 193],
        [195, 193, 192],
        [195, 193, 192]],

       ...,

       [[142,  30,  64],
        [143,  32,  64],
        [144,  34,  63],
        ...,
        [198, 194, 189],
        [197, 193, 188],
        [196, 192, 187]],

       [[135,  26,  58],
        [137,  28,  60],
        [141,  34,  61],
        ...,
        [198, 195, 190],
        [196, 193, 188],
        [193, 190, 185]],

       [[131,  22,  54],
        [132,  24,  53],
        [137,  30,  57],
        ...,
        [198, 195, 190],
        [195, 192, 187],
        [191, 188, 183]]

In [84]:
# Resize an image
if img.shape[1] > 600:
    img = imutils.resize(img, width=600)
clone = img.copy()
 
# Convert to grayscale
gray = cv2.cvtColor(clone, cv2.COLOR_BGR2GRAY)
 
# Threshold grayscaled image to get binary image
ret,gray_threshed = cv2.threshold(gray,150,255,cv2.THRESH_BINARY)
 
# Smooth an image
bilateral_filtered_image = cv2.bilateralFilter(gray_threshed, 5, 175, 175)
 

In [85]:

# Find edges
edge_detected_image = cv2.Canny(bilateral_filtered_image, 75, 200)
edge_detected_image

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [86]:

# Find contours
contours, _= cv2.findContours(edge_detected_image, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
 


In [ ]:
len(contours)

In [88]:
contour_list = []

for contour in contours:
    approx = cv2.approxPolyDP(contour,0.01*cv2.arcLength(contour,True),True)
    area = cv2.contourArea(contour)
    if ((len(approx) > 8) & (50000 > area > 10000) ):
        contour_list.append(contour)

In [ ]:

 
# Draw contours
cv2.drawContours(clone, contour_list, -1, (255,0,0), 2)
 
# Displaying the results
cv2.imshow("Original", img)
cv2.imshow('Smooth', bilateral_filtered_image)
cv2.imshow('Edge', edge_detected_image)
cv2.imshow('Objects Detected',clone)
cv2.waitKey(0)

In [ ]:
len(contours)

In [67]:
# find the biggest countour (c) by the area
c = max(contours, key = cv2.contourArea)
c

array([[[313,  97]],

       [[312,  98]],

       [[311,  98]],

       [[307, 102]],

       [[306, 102]],

       [[306, 103]],

       [[304, 105]],

       [[304, 111]],

       [[302, 113]],

       [[302, 114]],

       [[298, 118]],

       [[298, 121]],

       [[311, 121]],

       [[312, 120]],

       [[315, 120]],

       [[316, 119]],

       [[318, 119]],

       [[320, 117]],

       [[322, 119]],

       [[322, 120]],

       [[326, 120]],

       [[328, 118]],

       [[329, 118]],

       [[330, 117]],

       [[331, 117]],

       [[332, 116]],

       [[337, 116]],

       [[337, 115]],

       [[338, 114]],

       [[339, 114]],

       [[340, 115]],

       [[340, 116]],

       [[339, 117]],

       [[340, 118]],

       [[340, 119]],

       [[345, 124]],

       [[345, 132]],

       [[346, 133]],

       [[346, 140]],

       [[351, 140]],

       [[352, 141]],

       [[356, 141]],

       [[356, 132]],

       [[355, 131]],

       [[355, 129]],

       [[3

In [68]:
#gray = cv2.cvtColor(im,cv2.COLOR_BGR2GRAY)
#contours,h = cv2.findContours(gray,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)

final = np.zeros(img.shape,np.uint8)
mask = np.zeros(gray.shape,np.uint8)

#for i in range(0,len(contours)):
for i in range(0,len([c])):
    mask[...]=0
    cv2.drawContours(mask,[c],i,255,-1)
    cv2.drawContours(final,[c],i,cv2.mean(img,mask),-1)
    print(cv2.mean(img,mask))

cv2.imshow('im',img)
cv2.imshow('final',final)
cv2.waitKey(0)

(230.85325743200505, 171.6236559139785, 141.67172675521823, 0.0)


-1

!pip install webcolors

In [4]:
from webcolors import rgb_to_name

In [24]:
cv2.mean(img,mask)

(226.86963696369637, 151.73597359735973, 129.84323432343234, 0.0)

In [27]:
rgb_to_name((int(x) for x in cv2.mean(img,mask)[:3]))

ValueError: "#e29781" has no defined color name in css3.